version: "3.8"


services:
    manytask:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: manytask
        env_file: .env
        # volumes: (auto from docker container)
        #     - /cache
        #     - /solutions
